/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package afirmaws.services.nativos.ws.validarfirma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.4.0 2011-09-20T18:44:00.470+02:00 Generated source
 * version: 2.4.0
 * 
 */

@WebService(name = "Firma")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Firma {

  @WebResult(name = "ValidarFirmaReturn", partName = "ValidarFirmaReturn")
  @WebMethod(operationName = "ValidarFirma")
  public java.lang.String validarFirma(
      @WebParam(partName = "paramIn", name = "paramIn") java.lang.String paramIn);
}
