/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package afirmaws.services.dss.oasis.names.tc.dss._1_0.core.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2 2012-07-12T09:07:32.380+02:00 Generated source
 * version: 2.4.2
 * 
 */
@WebServiceClient(name = "DSSSignatureService",
    wsdlLocation = "file:/home/rus/desarrollo/Servicios-DSS-Afirma/esquemas/DSSAfirmaVerify.wsdl",
    targetNamespace = "urn:oasis:names:tc:dss:1.0:core:schema")
public class DSSSignatureService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE =
      new QName("urn:oasis:names:tc:dss:1.0:core:schema", "DSSSignatureService");
  public final static QName DSSAfirmaVerify =
      new QName("urn:oasis:names:tc:dss:1.0:core:schema", "DSSAfirmaVerify");
  static {
    URL url = null;
    try {
      url = new URL("file:/home/rus/desarrollo/Servicios-DSS-Afirma/esquemas/DSSAfirmaVerify.wsdl");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(DSSSignatureService.class.getName()).log(
          java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
          "file:/home/rus/desarrollo/Servicios-DSS-Afirma/esquemas/DSSAfirmaVerify.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public DSSSignatureService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public DSSSignatureService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public DSSSignatureService() {
    super(WSDL_LOCATION, SERVICE);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public DSSSignatureService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public DSSSignatureService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  // This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
  // API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
  // compliant code instead.
  public DSSSignatureService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   *
   * @return returns DSSSignature
   */
  @WebEndpoint(name = "DSSAfirmaVerify")
  public DSSSignature getDSSAfirmaVerify() {
    return super.getPort(DSSAfirmaVerify, DSSSignature.class);
  }

  /**
   * 
   * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
   *        Supported features not in the <code>features</code> parameter will have their default
   *        values.
   * @return returns DSSSignature
   */
  @WebEndpoint(name = "DSSAfirmaVerify")
  public DSSSignature getDSSAfirmaVerify(WebServiceFeature... features) {
    return super.getPort(DSSAfirmaVerify, DSSSignature.class, features);
  }

}
