/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-833
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.09.04 at 08:51:41 AM CEST
//

package es.mpt.dsic.inside.ws.service.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "enumeracionAlgoritmo")
@XmlEnum
public enum EnumeracionAlgoritmo {

  @XmlEnumValue("MD5")
  MD5("MD5"), @XmlEnumValue("SHA-1")
  SHA_1("SHA-1"), @XmlEnumValue("SHA-256")
  SHA_256("SHA-256"), @XmlEnumValue("SHA-384")
  SHA_384("SHA-384"), @XmlEnumValue("SHA-512")
  SHA_512("SHA-512");
  private final String value;

  EnumeracionAlgoritmo(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static EnumeracionAlgoritmo fromValue(String v) {
    for (EnumeracionAlgoritmo c : EnumeracionAlgoritmo.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
