/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package afirmaws.services.nativos.ws.validarcertificado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.2 2011-09-21T18:10:35.167Z Generated source version:
 * 2.4.2
 * 
 */
@WebService(name = "Validacion")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Validacion {

  @WebResult(name = "ValidarCertificadoReturn", partName = "ValidarCertificadoReturn")
  @WebMethod(operationName = "ValidarCertificado")
  public java.lang.String validarCertificado(
      @WebParam(partName = "parametrosIn", name = "parametrosIn") java.lang.String parametrosIn);
}
