/*
 * Copyright (C) 2012-13 MINHAP, Gobierno de España This program is licensed and may be used,
 * modified and redistributed under the terms of the European Public License (EUPL), either version
 * 1.1 or (at your option) any later version as soon as they are approved by the European
 * Commission. Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * more details. You should have received a copy of the EUPL1.1 license along with this program; if
 * not, you may find it at http://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 */

package es.mpt.dsic.eeutil.inside.consumer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import es.mpt.dsic.eeutil.inside.admin.model.InsideWSException;
import es.mpt.dsic.eeutil.inside.admin.model.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.0.3 2017-03-13T13:02:22.595+01:00 Generated source
 * version: 3.0.3
 * 
 */
@WebService(targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
    name = "AdminWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface AdminWebService {

  @WebResult(name = "numeroProcedimiento", targetNamespace = "")
  @RequestWrapper(localName = "listaNumeroProcedimiento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaNumeroProcedimiento")
  @WebMethod(action = "urn:listaNumeroProcedimiento")
  @ResponseWrapper(localName = "listaNumeroProcedimientoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaNumeroProcedimientoResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.NumeroProcedimiento> listaNumeroProcedimiento()
      throws InsideWSException;

  @WebResult(name = "estructuraCarpeta", targetNamespace = "")
  @RequestWrapper(localName = "listaEstructuraCarpeta",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaEstructuraCarpeta")
  @WebMethod(action = "urn:listaEstructuraCarpeta")
  @ResponseWrapper(localName = "listaEstructuraCarpetaResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaEstructuraCarpetaResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.EstructuraCarpeta> listaEstructuraCarpeta(
      @WebParam(name = "identificadorEstructura",
          targetNamespace = "") java.lang.String identificadorEstructura)
      throws InsideWSException;

  @WebResult(name = "estructuraCarpeta", targetNamespace = "")
  @RequestWrapper(localName = "altaEstructuraCarpeta",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaEstructuraCarpeta")
  @WebMethod(action = "urn:altaEstructuraCarpeta")
  @ResponseWrapper(localName = "altaEstructuraCarpetaResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaEstructuraCarpetaResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.EstructuraCarpeta altaEstructuraCarpeta(@WebParam(
      name = "estructuraCarpeta",
      targetNamespace = "") es.mpt.dsic.eeutil.inside.admin.model.EstructuraCarpeta estructuraCarpeta)
      throws InsideWSException;

  @WebResult(name = "Unidad", targetNamespace = "")
  @RequestWrapper(localName = "altaUnidadUsuario",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaUnidadUsuario")
  @WebMethod(action = "urn:altaUnidadUsuario")
  @ResponseWrapper(localName = "altaUnidadUsuarioResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaUnidadUsuarioResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Unidad altaUnidadUsuario(
      @WebParam(name = "nifUsuario", targetNamespace = "") java.lang.String nifUsuario,
      @WebParam(name = "codigoUnidadOrganica",
          targetNamespace = "") java.lang.String codigoUnidadOrganica,
      @WebParam(name = "numeroProcedimiento",
          targetNamespace = "") java.lang.String numeroProcedimiento)
      throws InsideWSException;

  @WebResult(name = "Aplicacion", targetNamespace = "")
  @RequestWrapper(localName = "bajaAplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.BajaAplicacion")
  @WebMethod(action = "urn:bajaAplicacion")
  @ResponseWrapper(localName = "bajaAplicacionResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.BajaAplicacionResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Aplicacion bajaAplicacion(@WebParam(
      name = "aplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.Aplicacion aplicacion)
      throws InsideWSException;

  @WebResult(name = "RespuestaEnvioJusticia", targetNamespace = "")
  @RequestWrapper(localName = "respuestaEnvioJusticia",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.RespuestaEnvioJusticia")
  @WebMethod(action = "urn:respuestaEnvioJusticia")
  @ResponseWrapper(localName = "respuestaEnvioJusticiaResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.RespuestaEnvioJusticiaResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.RespuestaEnvioJusticia2 respuestaEnvioJusticia(
      @WebParam(name = "codigoEnvio", targetNamespace = "") java.lang.String codigoEnvio)
      throws InsideWSException;

  @WebResult(name = "Unidad", targetNamespace = "")
  @RequestWrapper(localName = "getUnidadesUsuario",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.GetUnidadesUsuario")
  @WebMethod(action = "urn:getUnidadesUsuario")
  @ResponseWrapper(localName = "getUnidadesUsuarioResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.GetUnidadesUsuarioResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.Unidad> getUnidadesUsuario(
      @WebParam(name = "nifUsuario", targetNamespace = "") java.lang.String nifUsuario)
      throws InsideWSException;

  @RequestWrapper(localName = "limpiarDirectorioTemporal",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.LimpiarDirectorioTemporal")
  @WebMethod(action = "urn:limpiarDirectorioTemporal")
  @ResponseWrapper(localName = "limpiarDirectorioTemporalResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.LimpiarDirectorioTemporalResponse")
  public void limpiarDirectorioTemporal() throws InsideWSException;

  @WebResult(name = "Aplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/aplicacion")
  @RequestWrapper(localName = "altaAplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaAplicacion")
  @WebMethod(action = "urn:altaAplicacion")
  @ResponseWrapper(localName = "altaAplicacionResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaAplicacionResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Aplicacion altaAplicacion(@WebParam(
      name = "aplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.Aplicacion aplicacion)
      throws InsideWSException;

  @WebResult(name = "UnidadAplicacionEeutil", targetNamespace = "")
  @RequestWrapper(localName = "getUnidadAplicacionEeutil",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.GetUnidadAplicacionEeutil")
  @WebMethod(action = "urn:getUnidadAplicacionEeutil")
  @ResponseWrapper(localName = "getUnidadAplicacionEeutilResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.GetUnidadAplicacionEeutilResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.UnidadAplicacionEeutil> getUnidadAplicacionEeutil(
      @WebParam(name = "codigoUnidadOrganica",
          targetNamespace = "") java.lang.String codigoUnidadOrganica)
      throws InsideWSException;

  @WebResult(name = "CredencialesRemisionNube", targetNamespace = "")
  @RequestWrapper(localName = "actualizarCredencialesRemisionNube",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarCredencialesRemisionNube")
  @WebMethod(action = "urn:actualizarCredencialesRemisionNube")
  @ResponseWrapper(localName = "actualizarCredencialesRemisionNubeResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarCredencialesRemisionNubeResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.CredencialesRemisionNube actualizarCredencialesRemisionNube(
      @WebParam(name = "credencialesRemisionNube",
          targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.CredencialesRemisionNube credencialesRemisionNube)
      throws InsideWSException;

  @WebResult(name = "Aplicacion", targetNamespace = "")
  @RequestWrapper(localName = "crearActualizarSerialNumberCertificado",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.CrearActualizarSerialNumberCertificado")
  @WebMethod(action = "urn:crearActualizarSerialNumberCertificado")
  @ResponseWrapper(localName = "crearActualizarSerialNumberCertificadoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.CrearActualizarSerialNumberCertificadoResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Aplicacion crearActualizarSerialNumberCertificado(
      @WebParam(name = "idAplicacion", targetNamespace = "") java.lang.String idAplicacion,
      @WebParam(name = "serialNumberCertificado",
          targetNamespace = "") java.lang.String serialNumberCertificado)
      throws InsideWSException;

  @RequestWrapper(localName = "lanzaJobComunicacionTokenExpediente",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.LanzaJobComunicacionTokenExpediente")
  @WebMethod(action = "urn:lanzaJobComunicacionTokenExpediente")
  @ResponseWrapper(localName = "lanzaJobComunicacionTokenExpedienteResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.LanzaJobComunicacionTokenExpedienteResponse")
  public void lanzaJobComunicacionTokenExpediente() throws InsideWSException;

  @WebResult(name = "CredencialesRemisionNube", targetNamespace = "")
  @RequestWrapper(localName = "altaCredencialesRemisionNube",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaCredencialesRemisionNube")
  @WebMethod(action = "urn:altaCredencialesRemisionNube")
  @ResponseWrapper(localName = "altaCredencialesRemisionNubeResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaCredencialesRemisionNubeResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.CredencialesRemisionNube altaCredencialesRemisionNube(
      @WebParam(name = "credencialesRemisionNube",
          targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.CredencialesRemisionNube credencialesRemisionNube)
      throws InsideWSException;

  @WebResult(name = "numeroProcedimiento", targetNamespace = "")
  @RequestWrapper(localName = "altaNumeroProcedimiento",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaNumeroProcedimiento")
  @WebMethod(action = "urn:altaNumeroProcedimiento")
  @ResponseWrapper(localName = "altaNumeroProcedimientoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaNumeroProcedimientoResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.NumeroProcedimiento altaNumeroProcedimiento(
      @WebParam(name = "numeroProcedimiento",
          targetNamespace = "") java.lang.String numeroProcedimiento)
      throws InsideWSException;

  @WebResult(name = "Usuario", targetNamespace = "")
  @RequestWrapper(localName = "altaUsuario",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaUsuario")
  @WebMethod(action = "urn:altaUsuario")
  @ResponseWrapper(localName = "altaUsuarioResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaUsuarioResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Usuario altaUsuario(@WebParam(name = "usuario",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.Usuario usuario)
      throws InsideWSException;

  @RequestWrapper(localName = "eliminarUnidadAplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.EliminarUnidadAplicacion")
  @WebMethod(action = "urn:eliminarUnidadAplicacion")
  @ResponseWrapper(localName = "eliminarUnidadAplicacionResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.EliminarUnidadAplicacionResponse")
  public void eliminarUnidadAplicacion(
      @WebParam(name = "nombreAplicacion", targetNamespace = "") java.lang.String nombreAplicacion,
      @WebParam(name = "codigoUnidadOrganica",
          targetNamespace = "") java.lang.String codigoUnidadOrganica,
      @WebParam(name = "numeroProcedimiento",
          targetNamespace = "") java.lang.String numeroProcedimiento)
      throws InsideWSException;

  @RequestWrapper(localName = "eliminarUnidadUsuario",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.EliminarUnidadUsuario")
  @WebMethod(action = "urn:eliminarUnidadUsuario")
  @ResponseWrapper(localName = "infAdicionalAltaAppResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.InfAdicionalAltaAppResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.InfAdicional> eliminarUnidadUsuario(
      @WebParam(name = "nifUsuario", targetNamespace = "") java.lang.String nifUsuario,
      @WebParam(name = "codigoUnidadOrganica",
          targetNamespace = "") java.lang.String codigoUnidadOrganica,
      @WebParam(name = "numeroProcedimiento",
          targetNamespace = "") java.lang.String numeroProcedimiento)
      throws InsideWSException;

  @RequestWrapper(localName = "actualizarUnidadesDir3",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarUnidadesDir3")
  @WebMethod(action = "urn:comprobarDirectorioTemporal")
  @ResponseWrapper(localName = "actualizarUnidadesDir3Response",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarUnidadesDir3Response")
  public void actualizarUnidadesDir3() throws InsideWSException;

  @WebResult(name = "Unidad", targetNamespace = "")
  @RequestWrapper(localName = "altaUnidadAplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaUnidadAplicacion")
  @WebMethod(action = "urn:altaUnidadAplicacion")
  @ResponseWrapper(localName = "altaUnidadAplicacionResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaUnidadAplicacionResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Unidad altaUnidadAplicacion(
      @WebParam(name = "nombreAplicacion", targetNamespace = "") java.lang.String nombreAplicacion,
      @WebParam(name = "codigoUnidadOrganica",
          targetNamespace = "") java.lang.String codigoUnidadOrganica,
      @WebParam(name = "numeroProcedimiento",
          targetNamespace = "") java.lang.String numeroProcedimiento)
      throws InsideWSException;

  @WebResult(name = "Usuario", targetNamespace = "")
  @RequestWrapper(localName = "listaUsuarios",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaUsuarios")
  @WebMethod(action = "urn:listaUsuarios")
  @ResponseWrapper(localName = "listaUsuariosResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaUsuariosResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.Usuario> listaUsuarios()
      throws InsideWSException;

  @RequestWrapper(localName = "comprobarDirectorioTemporal",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ComprobarDirectorioTemporal")
  @WebMethod(action = "urn:comprobarDirectorioTemporal")
  @ResponseWrapper(localName = "comprobarDirectorioTemporalResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ComprobarDirectorioTemporalResponse")
  public void comprobarDirectorioTemporal() throws InsideWSException;

  @WebResult(name = "UsuarioResultadoBusqueda", targetNamespace = "")
  @RequestWrapper(localName = "listaUsuariosPaginado",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaUsuariosPaginado")
  @WebMethod(action = "urn:listaUsuariosPaginado")
  @ResponseWrapper(localName = "listaUsuariosPaginadoResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaUsuariosPaginadoResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.UsuarioResultadoBusqueda listaUsuariosPaginado(
      @WebParam(name = "filterPageRequest",
          targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.FilterPageRequest filterPageRequest)
      throws InsideWSException;

  @WebResult(name = "Aplicacion", targetNamespace = "")
  @RequestWrapper(localName = "listaAplicaciones",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaAplicaciones")
  @WebMethod(action = "urn:listaAplicaciones")
  @ResponseWrapper(localName = "listaAplicacionesResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ListaAplicacionesResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.Aplicacion> listaAplicaciones()
      throws InsideWSException;

  @WebResult(name = "Usuario", targetNamespace = "")
  @RequestWrapper(localName = "bajaUsuario",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.BajaUsuario")
  @WebMethod(action = "urn:bajaUsuario")
  @ResponseWrapper(localName = "bajaUsuarioResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.BajaUsuarioResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Usuario bajaUsuario(@WebParam(name = "usuario",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.Usuario usuario)
      throws InsideWSException;

  @WebResult(name = "SolicitudAccesoExpAppUrl", targetNamespace = "")
  @RequestWrapper(localName = "altaSolicitudAccesoExpAppUrl",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaSolicitudAccesoExpAppUrl")
  @WebMethod(action = "urn:altaSolicitudAccesoExpAppUrl")
  @ResponseWrapper(localName = "altaSolicitudAccesoExpAppUrlResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.AltaSolicitudAccesoExpAppUrlResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.SolicitudAccesoExpAppUrl altaSolicitudAccesoExpAppUrl(
      @WebParam(name = "solicitudAccesoExpAppUrl",
          targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.SolicitudAccesoExpAppUrl solicitudAccesoExpAppUrl)
      throws InsideWSException;

  @WebResult(name = "SolicitudAccesoExpAppUrl", targetNamespace = "")
  @RequestWrapper(localName = "actualizarSolicitudAccesoExpAppUrl",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarSolicitudAccesoExpAppUrl")
  @WebMethod(action = "urn:actualizarSolicitudAccesoExpAppUrl")
  @ResponseWrapper(localName = "actualizarSolicitudAccesoExpAppUrlResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarSolicitudAccesoExpAppUrlResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.SolicitudAccesoExpAppUrl actualizarSolicitudAccesoExpAppUrl(
      @WebParam(name = "solicitudAccesoExpAppUrl",
          targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.SolicitudAccesoExpAppUrl solicitudAccesoExpAppUrl)
      throws InsideWSException;

  @WebResult(name = "UnidadAplicacionEeutil", targetNamespace = "")
  @RequestWrapper(localName = "crearActualizarUnidadAplicacionEeutil",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.CrearActualizarUnidadAplicacionEeutil")
  @WebMethod(action = "urn:crearActualizarUnidadAplicacionEeutil")
  @ResponseWrapper(localName = "crearActualizarUnidadAplicacionEeutilResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.CrearActualizarUnidadAplicacionEeutilResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.UnidadAplicacionEeutil crearActualizarUnidadAplicacionEeutil(
      @WebParam(name = "unidadAplicacionEeutil",
          targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.UnidadAplicacionEeutil unidadAplicacionEeutil)
      throws InsideWSException;

  @WebResult(name = "Aplicacion", targetNamespace = "")
  @RequestWrapper(localName = "actualizarCredencialesEeetuilApp",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarCredencialesEeetuilApp")
  @WebMethod(action = "urn:actualizarCredencialesEeetuilApp")
  @ResponseWrapper(localName = "actualizarCredencialesEeetuilAppResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.ActualizarCredencialesEeetuilAppResponse")
  public es.mpt.dsic.eeutil.inside.admin.model.Aplicacion actualizarCredencialesEeetuilApp(
      @WebParam(name = "aplicacion",
          targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService") es.mpt.dsic.eeutil.inside.admin.model.Aplicacion aplicacion)
      throws InsideWSException;

  @WebResult(name = "InformacionAdicionalAltaApp", targetNamespace = "")
  @RequestWrapper(localName = "infAdicionalAltaApp",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.InfAdicionalAltaApp")
  @WebMethod(action = "urn:infAdicionalAltaApp")
  @ResponseWrapper(localName = "infAdicionalAltaAppResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.InfAdicionalAltaAppResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.InfAdicional> infAdicionalAltaApp()
      throws InsideWSException;

  @RequestWrapper(localName = "deleteEstructuraCarpeta",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.DeleteEstructuraCarpeta")
  @WebMethod(action = "urn:deleteEstructuraCarpeta")
  @ResponseWrapper(localName = "deleteEstructuraCarpetaResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.DeleteEstructuraCarpetaResponse")
  public void deleteEstructuraCarpeta(@WebParam(name = "identificadorEstructura",
      targetNamespace = "") java.lang.String identificadorEstructura) throws InsideWSException;

  @WebResult(name = "Unidad", targetNamespace = "")
  @RequestWrapper(localName = "getUnidadesAplicacion",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.GetUnidadesAplicacion")
  @WebMethod(action = "urn:getUnidadesAplicacion")
  @ResponseWrapper(localName = "getUnidadesAplicacionResponse",
      targetNamespace = "https://ssweb.seap.minhap.es/Inside/XSD/v1.0/WebService",
      className = "es.mpt.dsic.eeutil.inside.admin.model.GetUnidadesAplicacionResponse")
  public java.util.List<es.mpt.dsic.eeutil.inside.admin.model.Unidad> getUnidadesAplicacion(
      @WebParam(name = "nombreAplicacion", targetNamespace = "") java.lang.String nombreAplicacion)
      throws InsideWSException;
}
